# Generated by Django 3.2.16 on 2022-10-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('prize', models.CharField(blank=True, max_length=50, null=True, verbose_name='Награда')),
                ('likes', models.IntegerField(blank=True, null=True, verbose_name='Лайки')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
