# Generated by Django 3.2.16 on 2022-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.IntegerField(blank=True, null=True, verbose_name='Награда'),
        ),
    ]
