# Generated by Django 3.2.16 on 2022-10-08 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_alter_event_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
