# Generated by Django 3.2.16 on 2022-10-08 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20221008_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.CharField(max_length=1000, null=True, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.CharField(max_length=1000, null=True, verbose_name='Лайки'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
